# Generated by Django 3.2.18 on 2023-04-23 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courseapp', '0003_auto_20230422_1106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='materials_provided',
        ),
        migrations.DeleteModel(
            name='MaterialsProvided',
        ),
    ]
