# Generated by Django 3.2.18 on 2023-04-22 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courseapp', '0002_student_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialsProvided',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notebook', models.BooleanField(default=False)),
                ('pencil', models.BooleanField(default=False)),
                ('paper', models.BooleanField(default=False)),
                ('eraser', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='materials_provided',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courseapp.materialsprovided'),
        ),
    ]
